### PR TITLE
Add utf-8-BOM test.

### PR DESCRIPTION
**Pull request by philderbeast**
Here's a failing test for #50. It is the same as the utf-8 test but `Main.hs` has the byte order mark.

### CODE REVIEW

**Comment by philderbeast** [comment]
```
> snack build --package-yaml=tests/utf-8/package.yaml
/nix/store/mmp2pah12p71zpbjb505vy56xwx3q31z-hpack-build-json
```

```
> snack build --snack-nix=tests/utf-8/snack.nix
/nix/store/746ddr69qmvd0jvq8jv6iiw46i465wmh-snack-build-json
```

```
> snack build --package-yaml=tests/utf-8-BOM/package.yaml
...
' --arg packageYaml /Users/pdejoux/dev/src/haskell/snack/tests/utf-8-BOM/package.yaml
exit status: 100
stderr: building '/nix/store/q4cyx9kymhd0i5pvnp98frvgx0dsqydw-dependencies-json.drv'...
yr3ass1xqd8n27cjkcx8gzm61nzkmf82-import-parser: Could not parse module:
/nix/store/7fnlc85zx6bx38d5m907my481pxcm04f-Main.hs/Main.hs
 because lexical error at character '\65279'
```

```
> snack build --snack-nix=tests/utf-8-BOM/snack.nix
...
' --arg snackNix /Users/pdejoux/dev/src/haskell/snack/tests/utf-8-BOM/snack.nix
exit status: 100
stderr: building '/nix/store/q4cyx9kymhd0i5pvnp98frvgx0dsqydw-dependencies-json.drv'...
yr3ass1xqd8n27cjkcx8gzm61nzkmf82-import-parser: Could not parse module:
/nix/store/7fnlc85zx6bx38d5m907my481pxcm04f-Main.hs/Main.hs
 because lexical error at character '\65279'
```

**Comment by philderbeast** [comment]
I use [Beyond Compare](https://www.scootersoftware.com/). It shows the encoding of `Main.hs` as **Unicode (UTF-8) BOM**.

**Comment by nmattia** [comment]
Thanks, that'll help a lot. I'll have a go at fixing it this week.

**Comment by nmattia** [comment]
Superseded by #78

**Pull request closed without merging**
